#ifdef CPP_08_NOBUILD
#include <vector>

// Runtime system internal (not visible to users)
struct DestructorInfo {
  void* object_ptr;           // Address of the object
  void (*destructor)(void*);  // Pointer to the destructor function to call
  int priority;               // Reverse order of call
};
std::vector<DestructorInfo> cleanup_stack;  // Record of objects to clean up

// Register the destructor call info into cleanup_stack
void __runtime_register_destructor(void* obj_ptr, void (*destructor)(void*)) {
  DestructorInfo info;
  info.object_ptr = obj_ptr;
  info.destructor = destructor;
  info.priority = static_cast<int>(cleanup_stack.size());
  cleanup_stack.push_back(info);
}

MyClass::MyClass() {
  // ...constructor body...

  // Pseudo-code generated by the compiler
  __runtime_register_destructor(this, &MyClass::~MyClass);
}

MyClass::MyClass() {
  // ...constructor body...
  throw std::runtime_error("Error in constructor");  // Exception thrown
  // The following line is NOT executed because of the exception; therefore, no
  // destructor registration happens.
  __runtime_register_destructor(this, &MyClass::~MyClass);
}

#endif  // CPP_08_NOBUILD
