#include <iostream>
#include <string>

void Snippet1() {
#if 1 /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
  try {
    std::string str("Hello");
    str.at(10);  // This will throw std::out_of_range

    std::stoi(str);  // This will throw std::invalid_argument, but it won't be
                     // executed because the previous line throws an exception.
  } catch (const std::out_of_range& e) {
    std::cerr << "Out of range error: " << e.what() << std::endl;
  } catch (const std::invalid_argument& e) {
    std::cerr << "Invalid argument error: " << e.what() << std::endl;
  }
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 1 /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
  // The runtime allocates the exception object in an implementation-defined
  // location (not on the stack), allowing it to persist through stack unwinding
  // until it is handled.
  try {
    throw 1;  // it copies to exception storage as a temp object (1 is literal)
  } catch (int e) {  // int e = 1 (a copy from the exception storage)
    std::cerr << "Caught an exception with value: " << e << std::endl;
  }

  try {
    throw std::string("String exception");  // it copies to exception storage
  } catch (const std::string& e) {  // const std::string& e = std::string(...)
                                    // (a copy from the exception storage)
    std::cerr << "Caught a string exception: " << e << std::endl;
  }
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 1 /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
  try {
    std::string str_number;
    std::cout << "Enter a number: ";
    std::cin >> str_number;
    std::cout << "Entered: " << std::stoi(str_number);
  } catch (const std::invalid_argument& e) {
    // Re-throw the caught exception; the program will terminate because the
    // exception is passed to the runtime system.
    throw;
  }
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
}

#include <vector>

#if 1 /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
// Runtime system internal (not visible to users)
struct DestructorInfo {
  void* object_ptr;           // Address of the object
  void (*destructor)(void*);  // Pointer to the destructor function to call
  int priority;               // Reverse order of call
};
std::vector<DestructorInfo> cleanup_stack;  // Record of objects to clean up
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 1 /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
// Register the destructor call info into cleanup_stack
void __runtime_register_destructor(void* obj_ptr, void (*destructor)(void*)) {
  DestructorInfo info;
  info.object_ptr = obj_ptr;
  info.destructor = destructor;
  info.priority = static_cast<int>(cleanup_stack.size());
  cleanup_stack.push_back(info);
}
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 0  /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
MyClass::MyClass() {
  // ...constructor body...
  // Pseudo-code generated by the compiler
  __runtime_register_destructor(this, &MyClass::~MyClass);
}
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 0  /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
MyClass::MyClass() {
  // ...constructor body...
  throw std::runtime_error("Error in constructor");  // Exception thrown
  // The following line is NOT executed because of the exception; therefore, no
  // destructor registration happens.
  __runtime_register_destructor(this, &MyClass::~MyClass);
}
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 0  /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
class MyClass {
  int i_;
  int j_;

 public:
  MyClass() try : i_(0), j_(0) {
    if (i_ == 0) throw std::string("Integer is zero");
    // Case 1: i_ == 0 -> Exception thrown
    // Case 2: i_ != 0 -> No exception thrown
  } catch (const std::string& e) {
    std::cerr << "Handled: " << e << std::endl;
    // No re-throw -> Constructor completes normally
  }
  // Function-try block ends here!
  // -> Case 1 and Case 2 both reach here
  // -> Compiler generates destructor call registration at this point:
  // __runtime_register_destructor(this, &MyClass::~MyClass);
  ~MyClass() {
    // It will be called when the object is destroyed by cleanup_stack
  }
};
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */

#if 0  /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
class MyClass {
  int i_;
  int j_;

 public:
  MyClass() try : i_(0), j_(0) {
    if (i_ == 0) throw std::string("Integer is zero");
    // Case 1: i_ == 0 -> Exception thrown
    // Case 2: i_ != 0 -> No exception thrown
  } catch (const std::string& e) {
    throw;
    // Re-throw -> Constructor does not complete normally
  }
  // Function-try block ends here!
  // -> Only Case 2 reaches here (case 1 object is incomplete)
  // -> Compiler generates destructor call registration at this point:
  // __runtime_register_destructor(this, &MyClass::~MyClass);
  ~MyClass() {
    // It will be called when the object is destroyed by cleanup_stack
  }
};
#endif /* DO NOT CONTAIN THIS LINE IN THE MARKDOWN */
